pipeline:
  name: Primer
  identifier: Primer
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1730655910162
                    repoName: Th3Joel/SistemJugueteria.git
                    runAsUser: "1000"
                    build:
                      type: branch
                      spec:
                        branch: final
          caching:
            enabled: false
            paths:
              - /home/joel/runner/
          buildIntelligence:
            enabled: false
          sharedPaths:
            - ""
        delegateSelectors:
          - docker-delegate
