pipeline:
  name: Primer
  identifier: Primer
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: cd web && bun i
                    runAsUser: "1000"
          caching:
            enabled: false
            paths:
              - /home/joel/runner/
          buildIntelligence:
            enabled: false
        delegateSelectors:
          - docker-delegate
