pipeline:
  name: Build SistemJugueteria
  identifier: Build_Th3Joel_SistemJugueteria_1730663599754
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1730655910162
        repoName: Th3Joel/SistemJugueteria
        build: <+input>
