pipeline:
  name: Build SistemJugueteria
  identifier: Build_Th3Joel_SistemJugueteria_1730675083619
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencis from frontned
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Bash
                    command: cd web && bun install
              - step:
                  type: Run
                  name: Run build bun
                  identifier: Run_build_bun
                  spec:
                    shell: Sh
                    command: cd web && bun run build
              - step:
                  type: Run
                  name: install dependencies from goland
                  identifier: install_dependencies_from_goland
                  spec:
                    shell: Sh
                    command: go mod tidy
              - step:
                  type: Run
                  name: Build binario goland
                  identifier: Build_binario_goland
                  spec:
                    shell: Sh
                    command: go build -ldflags="-s -w" -o sis
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1730655910162
        repoName: Th3Joel/SistemJugueteria
        build: <+input>
