pipeline:
  identifier: Build_Th3Joel_SistemJugueteria_1734739262063
  name: Build SistemJugueteria
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1730655910162
        repoName: Th3Joel/SistemJugueteria
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Bash
                    command: whoami
                    runAsUser: "1000"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
