pipeline:
  identifier: Build_Th3Joel_SistemJugueteria_1730665846380
  name: Build SistemJugueteria
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1730655910162
        repoName: Th3Joel/SistemJugueteria
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Bash
                    command: go mod tidy
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: build bun
                  identifier: build_bun
                  spec:
                    shell: Bash
                    command: ls && uname -r && pwd
              - step:
                  identifier: gotestreport
                  name: go_aub
                  spec:
                    shell: Bash
                    command: go build -ldflags="-s -w" -o sis
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/report.xml
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
