pipeline:
  identifier: Build_Th3Joel_SistemJugueteria_1730665846380
  name: Build SistemJugueteria
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1730655910162
        repoName: Th3Joel/SistemJugueteria
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Bash
                    command: go mod tidy
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: .
                    tags:
                      - sis
                    dockerfile: .
                    context: .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
