// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCategoria = "Categorias"

// Categoria mapped from table <Categorias>
type Categoria struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Nombre      string    `gorm:"column:nombre;not null" json:"nombre"`
	Descripcion string    `gorm:"column:descripcion;not null" json:"descripcion"`
	CreatedAt   time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdateAt    time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
}

// TableName Categoria's table name
func (*Categoria) TableName() string {
	return TableNameCategoria
}
