// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCliente = "Cliente"

// Cliente mapped from table <Cliente>
type Cliente struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Phone   string `gorm:"column:phone" json:"phone"`
	Email    string `gorm:"column:email" json:"email"`
	Address string `gorm:"column:address" json:"address"`
	Surname  string `gorm:"column:surname" json:"surname"`
}

// TableName Cliente's table name
func (*Cliente) TableName() string {
	return TableNameCliente
}
