// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCliente = "Cliente"

// Cliente mapped from table <Cliente>
type Cliente struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	Nombre    string `gorm:"column:nombre;not null" json:"nombre"`
	Celular   string `gorm:"column:celular" json:"celular"`
	Correo    string `gorm:"column:correo" json:"correo"`
	Direccion string `gorm:"column:direccion" json:"direccion"`
	Apellido  string `gorm:"column:apellido" json:"apellido"`
}

// TableName Cliente's table name
func (*Cliente) TableName() string {
	return TableNameCliente
}
