// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDepartamento = "Departamentos"

// Departamento mapped from table <Departamentos>
type Departamento struct {
	ID     string `gorm:"column:id;primaryKey" json:"id"`
	Nombre string `gorm:"column:nombre;not null" json:"nombre"`
}

// TableName Departamento's table name
func (*Departamento) TableName() string {
	return TableNameDepartamento
}
