// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmpleo = "Empleos"

// Empleo mapped from table <Empleos>
type Empleo struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	PerfilUsuarioID string    `gorm:"column:perfilUsuarioId;not null" json:"perfilUsuarioId"`
	CategoriaID     string    `gorm:"column:categoriaId;not null" json:"categoriaId"`
	MunicipioID     string    `gorm:"column:municipioId;not null" json:"municipioId"`
	Titulo          string    `gorm:"column:titulo;not null" json:"titulo"`
	Descripcion     string    `gorm:"column:descripcion;not null" json:"descripcion"`
	Direccion       string    `gorm:"column:direccion;not null" json:"direccion"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdateAt        time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
}

// TableName Empleo's table name
func (*Empleo) TableName() string {
	return TableNameEmpleo
}
