// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameFavorito = "Favoritos"

// Favorito mapped from table <Favoritos>
type Favorito struct {
	ID              string `gorm:"column:id;primaryKey" json:"id"`
	PerfilUsuarioID string `gorm:"column:perfilUsuarioId;not null" json:"perfilUsuarioId"`
	EmpleoID        string `gorm:"column:empleoId;not null" json:"empleoId"`
}

// TableName Favorito's table name
func (*Favorito) TableName() string {
	return TableNameFavorito
}
