// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMunicipio = "Municipios"

// Municipio mapped from table <Municipios>
type Municipio struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	DepartamentoID string `gorm:"column:departamentoId;not null" json:"departamentoId"`
	Nombre         string `gorm:"column:nombre;not null" json:"nombre"`
}

// TableName Municipio's table name
func (*Municipio) TableName() string {
	return TableNameMunicipio
}
