// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePerfilUsuario = "PerfilUsuario"

// PerfilUsuario mapped from table <PerfilUsuario>
type PerfilUsuario struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	UserID      string    `gorm:"column:userId;not null" json:"userId"`
	MunicipioID string    `gorm:"column:municipioId" json:"municipioId"`
	Nombre      string    `gorm:"column:nombre;not null" json:"nombre"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Telefono    string    `gorm:"column:telefono;not null" json:"telefono"`
	Picture     string    `gorm:"column:picture;not null" json:"picture"`
	CreatedAt   time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdateAt    time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
	Bio         string    `gorm:"column:bio" json:"bio"`
}

// TableName PerfilUsuario's table name
func (*PerfilUsuario) TableName() string {
	return TableNamePerfilUsuario
}
