// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProveedore = "Proveedores"

// Proveedore mapped from table <Proveedores>
type Proveedore struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Nombre    string    `gorm:"column:nombre;not null" json:"nombre"`
	Direccion string    `gorm:"column:direccion" json:"direccion"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdateAt  time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
	Telefono  string    `gorm:"column:telefono" json:"telefono"`
	Correo    string    `gorm:"column:correo" json:"correo"`
}

// TableName Proveedore's table name
func (*Proveedore) TableName() string {
	return TableNameProveedore
}
