// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProveedore = "Proveedores"

// Proveedore mapped from table <Proveedores>
type Proveedore struct {
	ID        string    `gorm:"column:id;primaryKey;" json:"id"`
	Name    string    `gorm:"column:name;not null" json:"name"`
	Address string    `gorm:"column:address" json:"address"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdateAt  time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
	Phone  string    `gorm:"column:phone" json:"phone"`
	Email    string    `gorm:"column:email" json:"email"`
}

// TableName Proveedore's table name
func (*Proveedore) TableName() string {
	return TableNameProveedore
}
