// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePrueba = "Prueba"

// Account mapped from table <Account>
type Prueba struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Email     string    `gorm:"column:email;not null;unique" json:"email"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Role      string    `gorm:"column:role;not null;default:usuario" json:"role"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
	UpdateAt  time.Time `gorm:"autoUpdateTime"`
}

// TableName Account's table name
func (*Prueba) TableName() string {
	return TableNamePrueba
}
