// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameToken = "Token"

// Token mapped from table <Token>
type Token struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:userId;not null" json:"userId"`
	IP        string    `gorm:"column:ip" json:"ip"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
}

// TableName Token's table name
func (*Token) TableName() string {
	return TableNameToken
}
