// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	Email     string    `gorm:"column:email;unique;not null" json:"email"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Role      string    `gorm:"column:role;not null;default:vendedor" form:"role" json:"role"`
	UpdateAt  time.Time `gorm:"column:updateAt;not null" json:"updateAt"`
	Picture   string    `gorm:"column:picture;not null" json:"picture"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
